# Generated by Django 3.1.4 on 2020-12-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glavnyi', '0002_auto_20201214_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mather', models.CharField(max_length=11, verbose_name='mam')),
                ('father', models.CharField(max_length=11, verbose_name='pap')),
            ],
        ),
        migrations.CreateModel(
            name='Madi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, verbose_name='name')),
                ('parents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='glavnyi.parents')),
            ],
        ),
    ]
